export const POKEMONS_FETCH_REQUEST  = 'POKEMONS_FETCH_REQUEST';
export const POKEMONS_FETCH_SUCCESS  = 'POKEMONS_FETCH_SUCCESS';
export const POKEMONS_FETCH_FAILURE  = 'POKEMONS_FETCH_FAILURE';

export const POKEMON_MODAL_OPEN      = 'POKEMON_MODAL_OPEN';
export const POKEMON_MODAL_CLOSE     = 'POKEMON_MODAL_CLOSE';

export const POKEMON_DETAILS_FETCH_REQUEST = 'POKEMON_DETAILS_FETCH_REQUEST';
export const POKEMON_DETAILS_FETCH_SUCCESS = 'POKEMON_DETAILS_FETCH_SUCCESS';
export const POKEMON_DETAILS_FETCH_FAILURE = 'POKEMON_DETAILS_FETCH_FAILURE';
